# 使用 Nginx 作为基础镜像
FROM nginx:alpine

# 删除默认 nginx 网站内容
RUN rm -rf /usr/share/nginx/html/*

# 直接拷贝本地已编译好的前端资源
COPY dist/ /usr/share/nginx/html/

# 默认使用 80 端口
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]